Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-07b4f3c02c7f83d59"
      InstanceType: t2.micro
      KeyName: korey-earl-aws
      SecurityGroups:
      - launch-wizard-2
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            sudo apt-get update
            sudo apt-get install python3-pip -y
            pip3 install awscli --upgrade
            sudo apt-get install docker.io -y
            sudo systemctl start docker
            sudo systemctl enable docker
