Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-07b4f3c02c7f83d59"
      InstanceType: t2.micro
      KeyName: korey-earl-aws
      SecurityGroups:
      - launch-wizard-2
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            cat "Hello World" > /tmp/test.txt
