Parameters:
  PostgresPwd:
    Type: String
  AuthCode:
    Type: String
  ImageId:
    Type: String
Resources:
  BrickDBInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - BrickDBServer
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: !Ref ImageId
      InstanceType: t2.micro
      KeyName: korey-earl-aws
      SecurityGroups:
      - launch-wizard-2
      IamInstanceProfile: !Ref BrickDBInstanceProfile
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            #echo '* libraries/restart-without-asking boolean true' | sudo debconf-set-selections
            sudo apt-get update -y
            # Install AWS CLI
            sudo sh -c 'DEBIAN_FRONTEND=noninteractive apt-get install python3-pip -y'
            pip3 install awscli --upgrade
            # Install Docker
            sudo apt-get install docker.io -y
            sudo systemctl start docker
            sudo systemctl enable docker
            # Install Postgresql
            sudo sh -c 'DEBIAN_FRONTEND=noninteractive apt-get install postgresql postgresql-client -y'
            echo "host all all 0.0.0.0/0 md5" | sudo tee -a /etc/postgresql/10/main/pg_hba.conf
            echo "listen_addresses = '*'" | sudo tee -a /etc/postgresql/10/main/postgresql.conf
            sudo service postgresql restart
            sudo -u postgres psql -c "ALTER USER postgres PASSWORD '${PostgresPwd}';"
            sudo -u postgres psql -c "CREATE DATABASE brick;"
            # Start App
            sudo docker run -d \
              -e POSTGRES_PASSWORD=${PostgresPwd} \
              -e AUTH_CODE=${AuthCode} \
              -e STORAGE=POSTGRESQL \
              -e STORAGE_HOST=172.17.0.1 \
              -p 5000:5000 \
              stujfiter/brick-api
